### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by GarethH96** [monero-project/monero-gui#1308]
I get this error when trying to run `./start.sh`:
```
This application failed to start because it could not find or load the Qt platform plugin "wayland"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
./start-gui.sh: line 7:  3165 Aborted                 (core dumped) "$SCRIPT_DIR"/monero-wallet-gui
```

**Comment by skftn** [comment]
Could you try running this command first: `export QT_QPA_PLATFORM=xcb`

Afterwards `./start.sh` - I'd like to know what happens.

**Comment by pazos** [comment]
@GarethH96: qt bundled in official binaries only support xcb platform plugin for linux ATM.

if you build monero-wallet-gui from source you'll get more plugins. In my system (Ubuntu 16.04 | x64 | official qt 5.10.1)
```
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```
official qt binaries don't distribute wayland, but I'm sure new distros build qt with support  for wayland.

So, you can build from source following the readme an give us some feedback :)

**Comment by GarethH96** [comment]
@skftn That actually works, but really would prefer to have Wayland support.

@pazos I use Antergos KDE which is Arch Linux based, so I have the latest software. Tried cloning and compiling the source of v0.12. At first, it appears to work fine, but when I deleted the .bitmonero that was made from the pre-compiled version I get a window that only displays the text 'Weclome to Monero! Please choose a language and regional format' and the rest of the window is completely empty, no matter weather it is on Wayland or X11.

**Comment by skftn** [comment]
Closing as we will not support Wayland at this point in time, #1357 has a fix that forces xcb.

+resolved

**Comment by cirosantilli** [comment]
Sad I still get the issue on Ubuntu 25.10 wayland, it was working on 25.04 previously:

```
~/bin/monero-gui-v0.18.4.4
2025-11-29_08-09-21@ciro@ciro-p14s$ QT_QPA_PLATFORM=xcb ./monero-wallet-gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Authorization required, but no authorization protocol specified

qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, xcb, minimal, offscreen, vnc.

Aborted
~/bin/monero-gui-v0.18.4.4
2025-11-29_08-09-27@ciro@ciro-p14s$ QT_QPA_PLATFORM=wayland ./monero-wallet-gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, xcb, minimal, offscreen, vnc.

Aborted
```

Edit: I have the crazy impression that:

```
sudo apt install monero
```

fixed it, despit me still using the manually downloaded prebuilt. Maybe a system dependency was missing?
