### ISSUE TITLE
Why does monero-gui now need libhidapi?

### ISSUE THREAD

**Issue by oneEyedCharlie** [monero-project/monero-gui#1683]
The purpose of that package is to access bluetooth and weird keyboards.  Why does monero-gui now need that?  I'm sure there is a reasonable explanation, but it seems suspicious to want access to non-standard input devices.

**Comment by xiphon** [comment]
Ledger support. Using hidapi instead of pcsclite now.

**Comment by oneEyedCharlie** [comment]
Ah ok.  Thank you.  Now I have to figure out how to get that into Linux Mint 19, which doesn't have any of the hidapi packages.

**Comment by xiphon** [comment]
Actually don't close this. Looks like a correct issue. The library should be statically linked.

**Comment by oneEyedCharlie** [comment]
Done.

**Comment by skftn** [comment]
Fixed since https://github.com/monero-project/monero-gui/commit/a34608a801e462ae9d732452ebd25fdc592aebb7 (master) https://github.com/monero-project/monero-gui/blob/release-v0.13/monero-wallet-gui.pro#L301 (release v0.13 branch)

v0.13.0.4 should be out soon.

**Comment by dEBRUYNE-1** [comment]
+resolved

**Comment by oneEyedCharlie** [comment]
This should be re-opened?  I just downloaded the new 0.13.0.4 version, and am still getting the error.

`error while loading shared libraries: libhidapi-libusb.so.0: cannot open shared object file: No such file or directory`

I know I can install libhidapi-dev and make this go away, but I figured I should still let you know.

**Comment by skftn** [comment]
Thanks for the headsup. We are aware, currently struggling getting `libhidapi` statically included.
