### ISSUE TITLE
unable to connect to monero network

### ISSUE THREAD

**Issue by jasonwee** [monero-project/monero-gui#2443]
When launch the app, this is shown

`Connected daemon is not compatible with GUI. Please upgrade or connect to another daemon`

using current version, 0.14.1.0, any fix for this?

**Comment by selsta** [comment]
Are you using simple mode? If no,  local/remote node?

**Comment by jasonwee** [comment]
Not sure what you mean by your questions. But it only happen since today.

i start using the following command line,

`./start-gui.sh`

and then it show that error messages.

**Comment by SamsungGalaxyPlayer** [comment]
What does it say under settings -> info? Make sure to remove any sensitive details if you send screenshots.

![image](https://user-images.githubusercontent.com/12520755/68802117-ec387880-0622-11ea-8d5f-44bc5ba375ba.png)

**Comment by jasonwee** [comment]
Sure, thank you for looking and below are the screenshots.

![Screenshot from 2019-11-14 09-31-32](https://user-images.githubusercontent.com/3326279/68828376-67ac2f80-06e0-11ea-8b8e-6aee09602328.png)
![Screenshot from 2019-11-14 09-31-43](https://user-images.githubusercontent.com/3326279/68828377-67ac2f80-06e0-11ea-82de-61e8bd38adcf.png)

**Comment by jasonwee** [comment]
I have been using this app for a while now and it rocks! But this problem only come yesterday and I'm puzzled as this is the current latest version. Not sure what should I do, can you tell me if I have to do anything manually?

**Comment by SamsungGalaxyPlayer** [comment]
Is the reason because it's connected to a 0.15 node?

**Comment by jasonwee** [comment]
I have no idea, there is no changes on configuration other than just launching the app. Do you mean I have to upgrade the app or use another configuration?

**Comment by selsta** [comment]
I would suggest restarting a couple times until the error goes away. Not ideal but v0.15 GUI should be out soon.

**Comment by jasonwee** [comment]
Restart? Tried many many times, when it does not work, it don't work.

What I did, start again the app by moving these directory and resetup the wallet.
```
user@localhost:$ mv Monero/ Monero-backup
user@localhost:$ mv .bitmonero/ .bitmonero-backup/
user@localhost:$ 
```

Resync everything and it seem to work again. Awesome!

**Comment by jasonwee** [comment]
Unfortunately it happen again :'( guess I will have to wait for the new release. Do you know if the new release will fix current problem that I'm facing?

**Comment by selsta** [comment]
Go to the wizard, select "Change wallet mode" and then select Advanced mode.

Open you wallet again, go to Settings -> Node -> Select remote node and enter the following:

Address: `uwillrunanodesoon.moneroworld.com`
Port: `18089`

This should work.

**Comment by EmbeddedAndroid** [comment]
I hit this today as well, when I updated my remote nodes to v0.15.0.0 fwiw. Seems that the new daemon code has broken compatibility with the older GUI.

**Comment by selsta** [comment]
v0.15.0.1 is tagged, binaries should be out in the next 24-48 hours.

**Comment by EmbeddedAndroid** [comment]
> v0.15.0.1 is tagged, binaries should be out in the next 24-48 hours. This issue should be resolved then.

Great, thank you!

**Comment by dEBRUYNE-1** [comment]
This should be fixed with the GUI v0.15.0.1 release.

**Comment by dEBRUYNE-1** [comment]
+resolved

**Comment by djp1701** [comment]
Unfortunately, the issue persists with 0.15.0.1 as I downloaded and installed yesterday and am experiencing the same behavior as jasonwee...been using the Monero wallet for years and this only started happening yesterday when I went to update the app in preparation for RandomX

**Comment by selsta** [comment]
@djp1701 Which remote node are you connecting to? Try node.xmr.to:18081

**Comment by EmbeddedAndroid** [comment]
I can confirm v0.15.0.1 gui works with my v0.15.0.1 local daemon now, thanks!
